@startuml
skinparam wrapwidth 300
skinparam classfontname consolas
skinparam classfontsize 16
skinparam classattributefontname cascadia code
skinparam classattributefontsize 12
left to right direction

package SpellCasting {

    class SpellPool {
        - spellPool : SpellSprite[]
        ---
        + registerSpriteWithLayer(SpellSprite spellSprite) : void
        + getSpell(SpellType spellType) : SpellSprite
        + createSpell(SpellType spellType) : SpellSprite
        + haveSpellInPool(SpellType spellType) : SpellSprite
    }

    class SpellSprite {
        - id : int
        - inUse : bool
        - spellAsset : SpellAsset
        - targetsId : int[]
        - timeEffect : double
        - statingTime : int
        ---
        + createAnimation()
        + effecting()
        + endEffect()
        + update()
    }

    class SpellLayer {
        - controller : SpellController
        - ctor(SpellLayerController controller)
        - addTouchListener()
    }

    class SpellLayerController {
        - spellPool : SpeelPool
        ---
        - castSpell(cc.Point targetPosition, SpellType spellType) : void
        - effectedMonsterTargetForSpell(cc.Point spellPosition) : int[]
        - effectedTowerTargetForSpell(cc.Point spellPosition) : int[]
    }

    class "Cầu Lửa" extends SpellSprite {
        - damage : double
        + effecting()
    }
    class "Đóng Băng" extends SpellSprite {
        - damage : double
        + efecting()
    }
    class "Tăng Tốc" extends SpellSprite {
        - speed : double
        + effecting()
    }
    class "Hồi Máu" extends SpellSprite {
        - healthSpeed : double
        + effecting()
    }
    class "Sức mạnh" extends SpellSprite {
        - additionPercent : double
        + effecting()
    }

    SpellLayer "1" --* "1" SpellLayerController
    SpellSprite "n" -d-* "1" SpellPool
    SpellPool "1" --* SpellLayerController



}
@enduml