@startuml
skinparam wrapwidth 300
skinparam classfontname consolas
skinparam classfontsize 16
skinparam classattributefontname cascadia code
skinparam classattributefontsize 14
left to right direction
package Tower {

    class TowerLayerController {
        - towerSequence : Tower[]
        - towerLayer : TowerLayer
        ---
        + findingTargetForTower(cc.Point position, AttackMode attackMode) : void
        + canUpdateTowerInIndex(cc.Point index, CardType cardType) : bool
        + updateTowerWithIndex(cc.Point index)
        + towerTargeted() : void
        ---
        # thực hiện hiển thị các trụ lên sân
        # thực hiện cập nhât và xử lý hình ảnh của các trụ
        # thực hiện giao tiếp với MonsterLayer để lấy được danh sách quái
        # thực hiện các cử chỉ với trụ (trong đó bao gồm cả nâng cấp và điều chỉnh chế độ chọn mục tiêu của trụ)

    }

    class TowerLayer {
        - controller : TowerLayerController
        ---
        + ctor(TowerLayerController controller)
        + addTouchListener() : void
        + addChilds(TowerSprite[])
        + update() : void
        ---
        # chỉ sử dụng để hiển thị trụ
    }

    class TowerSprite {
        - position : cc.Point
        - id : int
        - range : float
        - level : int
        - canAttack : bool
        - effectd : TowerEffecting[]
        - type : TowerType
        ---
        + fire() : void
        + createAnimation() : void
        + changeTarget() : void
        + updateSprite() : void
        + update()
        ---
        # bắt được danh sách các loại quái hiên tại đang ở trong phạm vi
        # năng lượng sử dụng để đặt khác nhau
        # tháp có khả năng tiến hóa được
        # hệ thống có nhiều các ưu tiên cho quái lựa chọn
        # hệ thống đạn bắn - 2 loại
        # 7 loại trụ, mỗi loại trụ có các loại đạn khác nhau
        # loại đạn có thể là tầm rộng hoặc là một mục tiêu duy nhất
        # có thể có trụ không bắn ra đạn - trụ hỗ trợ
        # có thể hủy tháp đã chọn
        # có thể có được danh sách quái hiện tại đang ở vị trí nào trên bản đồ
        # có các phương thức thực hiện các các lựa chọn quái vật khác nhau
    }

    class SupportTower extends TowerSprite {
        - targetType : Monster | Tower
        - targetIds : int[]
        ---
        + fire() : void
    }

    class AttackTower extends TowerSprite {
        - attackSpeed : float
        - dame : float
        - haveTarget : bool
        - bulletPool : BulletPool
        - targetId : int
        - attackMode : AttackMode
        ---
        + fire() : void
        + canTargetOnThis(cc.Point position) : bool
        + untarget() : void
    }

    class "Pháo Cú Tower" {}
    class "Quạ Pháp Sư Tower" {}
    class "Ếch Đồ Tể Tower" {}
    class "Thỏ Xả Nhớt Tower" {}
    class "Gấu Bắc Cực Tower" {}

    package Bullet {
        
        class BulletPool {
            - bulletPool : BulletSprite[]
            ---
            + registerSpriteWithLayer(BulletSprite bulletSprite) : void
            + getBullet(BulletType bulletType) : BulletSprite
            + createBullet(BulletType bulletType) : BulletSprite
            + haveBulletInPool(BulletType bulletType) : BulletSprite
        }

        class BulletSprite  {
            - canUseTowerSkill : bool
            - inUsed : bool
            - speed : int
            - damage : double
            - range : double
            - towerPosition : cc.Point
            - type : Bullet.PosisionBase | Bullet.TargetBase
            ---
            + create() : BulletSprite
            + animate() : void
            + createAnimation() : void
            + effecting() : void
            + exploded() : void
            - usingSkill() : void
            ---
            # mỗi tòa tháp sẽ có một loại đạn riêng, override lại effecting
            # mỗi loại đạn sẽ có các hành vi khách nhau như là nổ lan, gây đống băng, ...
            # đạn sẽ có các thuộc tính cơ bản như là tốc độ bay, chuỗi animation, và sức sát thương
        }

        class "Pháo Cú Bullet" extends BulletSprite {
            - type : Bullet.TargetBase
            - exploded() : void
            - effecting() : void
            - usingSkill() : void
        }
        class "Quạ Pháp Sư Bullet" extends BulletSprite {
            - type : Bullet.PosisionBase
            - exploded() : void
            - effecting() : void
            - usingSkill() : void
        }
        class "Ếch Đồ Tể Bullet" extends BulletSprite {
            - type : Bullet.PosisionBase
            - exploded() : void
            - effecting() : void
            - usingSkill() : void
        }
        class "Thỏ Xả Nhớt Bullet" extends BulletSprite{
            - type : Bullet.PosisionBase
            - effecting() : void
            - exploded() : void
            - usingSkill() : void
        }
        class "Gấu Bắc Cực Bullet" extends BulletSprite{
            - type : Bullet.TargetBase
            - effecting() : void
            - exploded() : void
            - usingSkill() : void
        }


    }

    "Pháo Cú Tower" -right--|> TowerSprite
    "Quạ Pháp Sư Tower" -right--|> TowerSprite
    "Ếch Đồ Tể Tower" -right--|> TowerSprite
    "Thỏ Xả Nhớt Tower" -right--|> TowerSprite
    "Gấu Bắc Cực Tower" -right--|> TowerSprite


    TowerLayerController "1" *-- "n" TowerSprite
    TowerLayer "1" -right-* "1" TowerLayerController

    AttackTower "1" *-left- "1" BulletPool
    BulletSprite "n" -up-* "1" BulletPool
}
@enduml