@startuml
skinparam wrapwidth 300
skinparam classfontname consolas
skinparam classfontsize 16
skinparam classattributefontname cascadia code
skinparam classattributefontsize 12

package UI {
    class UILayerController {
        - energy : int
        - cardSequence : Card[]
        - cardSpriteSequence : CardSprite[]
        - nextCard : Card
        - userInfo : UserInfo
        - selectedIndex : int
        ---
        + usingCard() : void
        + randomNextCard() : Card
        + updateEnerge() : void
        + increaseEnergy(int additionEnergy) : void
        + foldCardWithIndex(int index) : void
        + cardSelected(int index) : void
        ---
        # chứa thông tin về các thẻ bài quái tiếp theo sẽ được chọn của người chơi
        # chứa năng lượng hiện tại của người chơi
        # hiển thị các thông tin liên quan tới màn chơi
    }

    class UILayer {
        - controller : UILayerController
        + init(UILayerController parent)
        + addTouchListener()
    }

    class CardSprite {
        - type : CardType
        - level : int
        ---
        + createCardSprite() : void
        + changeCardType() : void
    }

    UILayerController "1" *-- "1" UILayer
    CardSprite "n" -r-* "1" UILayer
}
@enduml