@startuml
actor Player as player
boundary UILayer as uiLayer
boundary MapLayer as mapLayer
control MapController as mapController
control BattleController as battleController
control Server as server

player -> uiLayer : cardSelected(index)
uiLayer -> mapLayer : cardSelected(Card)
mapLayer -> mapLayer : changCursorSprite()

player -> uiLayer : touchListener()
uiLayer -> mapController : canPlantHere()
mapController -> uiLayer : true
uiLayer -> mapController : plantTower(position)
mapController -> mapLayer : updateMapLayer()
mapLayer -> battleController : updateMapLayer()
battleController -> server : newGameState
@enduml