@startuml
actor Player as Player
boundary UILayer as UILayer
boundary MapLayer as MapLayer
boundary TowerLayer as TowerLayer

Player -> UILayer : cardSelected(index)
UILayer -> MapLayer : cardSelected(Card)
MapLayer -> MapLayer : changCursorSprite()

Player -> UILayer : selectedPosition()
UILayer -> TowerLayer : canUpdateTowerInIndex(index, cardType)
TowerLayer -> UILayer : true
UILayer -> TowerLayer : updateTowerWithIndex(index)
UILayer -> UILayer : usingCard()

@enduml