@startuml

skinparam wrapwidth 300
skinparam classfontname cascadia code
skinparam classfontsize 16
skinparam classattributefontname cascadia code
skinparam classattributefontsize 12
left to right direction


package BattleHandler {
    class BattleHandler {
        - battle : Battle
        + updateGameState() : void
        + plantTowerHandle() : void
        + upgradeTowerHandle() : void
        + monsterSpawnHandle() : void
        + towerSpawnHandle() : void
        + spellSpawnHandle() : void
        + clientNeedUpgrade() : void
        + updateGameState1(GameState clientGameState) : void
        + updateGameState2(GameState clientGameState) : void
    }
}


package Model {

    class Battle {
        - battleId : int
        - gameState1 : GameState
        - gameState2 : GameState
        - userInfo1 : UserInfo
        - userInfo2 : UserInfo
        ---
        + checkingNewGameState() : bool
        + generateMap() : void
        + isValidGameState() : int
    }

    class UserInfo {
        - email : String
        - name : String
        - displayName : String
        - password : String
        - resourceProfile : ResourceProfile
        - battleProfile : BattleProfile
        - treasure :  Treasure[]
    }

    class Treasure {
        - type : TreasureType
        - items : Item[]
        - remainingTime : double
        - open()
    }

    class ResourceProfile {
        - activeCard :  Card[]
        - gem : int
        - coin : int
        - frame : int
    }

    class Card {
        - isActive : bool
        - level : bool
        - pieces : int
    }
    Card "n" --* "1" ResourceProfile
    Treasure "n" --* "1" UserInfo
    UserInfo "2" --* "1" Battle
}
Battle --* BattleHandler

@enduml